### ISSUE TITLE
Resizing of the slideshow indicators

### ISSUE THREAD

**Issue by TheCoderGuru** [catherineisonline/pizza-time-with-react#1]
Hey Catherine, just visited your site and it looks professionally made so excellent job with that.

I have a small suggestion that the slideshow indicators be a bit smaller to approximately 18px on both the `height` and `width` css properties.

I have provided an image below to give you an idea how it will look

![image](https://user-images.githubusercontent.com/86580705/161569318-86fb737b-2359-45c9-ab15-714a006cacd7.png)

I hope this is helpful

Cheers

Happy coding
👍

**Comment by catherineisonline** [comment]
@TheCoderGuru Thank you for the suggestions. Quick question, what is the exact reason it has to be smaller? Thank you

**Comment by TheCoderGuru** [comment]
> @TheCoderGuru Thank you for the suggestions. Quick question, what is the exact reason it has to be smaller? Thank you

The reason is due to the appearance on mobile devices. I find it can be slightly smaller to look a bit better however that's just my preference. I would recommend previewing it on a mobile device to better understand from my viewpoint.

Cheers and happy coding

**Comment by catherineisonline** [comment]
Sounds reasonable. Just wondered whether it's due to something specific. Thank you!

**Comment by catherineisonline** [comment]
Updated dot sizes for header carousel
