### ISSUE TITLE
dropdown text color is same as dropdown background color

### ISSUE THREAD

**Issue by aayusranjan** [catherineisonline/pizza-time-with-react#2]
![Screenshot 2022-10-06 120849](https://user-images.githubusercontent.com/63737303/194231875-782efad8-1a56-4333-ad6d-d55fce8e36b8.png)

**Comment by catherineisonline** [comment]
@aayusranjan which browser did you check on?

**Comment by aayusranjan** [comment]
@catherineisonline Chrome

**Comment by catherineisonline** [comment]
> @catherineisonline Chrome

Thanks. Strangely, I could not reproduce this issue on Chrome or Safari. Did some small changed but I do not know whether it helped.
