### ISSUE TITLE
Improve the Design and Aesthetics of the Contact Page

### ISSUE THREAD

**Issue by SumitThakur1600** [catherineisonline/pizza-time-with-react#32]
The current Contact page design could benefit from improvements to make it more visually appealing and user-friendly. The goal is to enhance the layout, typography, and overall styling to provide a better experience for users.

Suggestions:

Improve the layout with better spacing and alignment for form elements.
Use more engaging typography and colors to match the overall website design.
Add icons or visual cues for each form field (e.g., email, phone number).
Make the page mobile-responsive for a seamless experience across devices.
Include a background image or a section with a subtle texture to make the page more dynamic.
Add hover effects or subtle animations for buttons and inputs to improve interaction.
Ensure form fields are clearly labeled and accessible.
Expected Outcome: A visually attractive and user-friendly Contact  page that aligns with the overall design of the website and encourages user engagement.

Please assign me this issue

**Comment by catherineisonline** [comment]
@SumitThakur1600 Thank you for your attempt to improve the website. This project serves as a way to showcase MY skills, not someone else's. However, the enthusiasm to improve someone else's projects is always welcome and can be shared in the [discussions](https://github.com/catherineisonline/pizza-time-with-react/discussions) section. Thank you!
